<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <AssemblyName>ApiInspector</AssemblyName>
        <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    </PropertyGroup>

    <PropertyGroup>
        <LangVersion>preview</LangVersion>
        <ApplicationIcon>app.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\old_ApiInspector.NetFramework\FpExtensions.cs" Link="FpExtensions.cs" />
        <Compile Include="..\old_ApiInspector.NetFramework\GlobalUsings.cs" Link="GlobalUsings.cs" />
        <Compile Include="..\old_ApiInspector.NetFramework\MetadataNode.cs" Link="MetadataNode.cs" />
        <Compile Include="..\old_ApiInspector.NetFramework\Plugin.cs" Link="Plugin.cs" />
        <Compile Include="..\old_ApiInspector.NetFramework\ProcessHelper.cs" Link="ProcessHelper.cs" />
        <Compile Include="..\old_ApiInspector.NetFramework\Program.cs" Link="Program.cs" />
        <Compile Include="..\old_ApiInspector.NetFramework\ReflectionHelper.cs" Link="ReflectionHelper.cs" />
        <Compile Include="..\old_ApiInspector.NetFramework\JsonConverterForPropertyInfo.cs" Link="JsonConverterForPropertyInfo.cs" />
		<Compile Include="..\old_ApiInspector.NetFramework\AsyncLogger.cs" Link="AsyncLogger.cs" />
        <Compile Include="..\old_ApiInspector.NetFramework\JsonInternalAssigner.cs" Link="AsyncLogger.cs" />
        <Compile Include="..\old_ApiInspector.NetFramework\Invocation.Shared.cs" Link="Invocation.Shared.cs" />
        <Compile Include="..\shared\AssemblyModel.cs" Link="Shared\AssemblyModel.cs" />
        <Compile Include="..\Shared\AssemblyModelHelper.cs" Link="Shared\AssemblyModelHelper.cs" />
        <Compile Include="..\shared\toolbox\Result.cs" Link="Shared\Toolbox\Result.cs" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="app.ico" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="BOA.Compatibility" Version="1.*" />
    </ItemGroup>


    <ItemGroup>
      <Folder Include="Shared\Toolbox\" />
    </ItemGroup>
    <PropertyGroup>
        <PostBuildEvent>
            copy /y "$(OutDir)$(AssemblyName).*" D:\BOA\tools\ApiInspector\ApiInspector.NetCore\
        </PostBuildEvent>
    </PropertyGroup>

</Project>
