<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ApplicationIcon>app.ico</ApplicationIcon>
    </PropertyGroup>

    <PropertyGroup>
        <LangVersion>preview</LangVersion>
        <StartupObject>ApiInspector.WebUI.Program</StartupObject>
    </PropertyGroup>

    <ItemGroup>
      <Content Remove="ApiInspector.WebUI.Config.json" />
    </ItemGroup>

    <ItemGroup>
      <None Include="ApiInspector.WebUI.Config.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Resources\*.*" />
    </ItemGroup>

    <ItemGroup>
      <Compile Include="..\Shared\AssemblyModel.cs" Link="Shared\AssemblyModel.cs" />
      <Compile Include="..\Shared\Toolbox\Result.cs" Link="Shared\Toolbox\Result.cs" />
      <Compile Include="..\Shared\Toolbox\Result.IAsyncEnumerable.cs" Link="Shared\Toolbox\Result.IAsyncEnumerable.cs" />
    </ItemGroup>
	
    <ItemGroup>
      <Folder Include="Properties\" />
    </ItemGroup>


    <ItemGroup>




        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />


        
        <PackageReference Include="Mono.Cecil" Version="0.11.6" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <Reference Include="ReactWithDotNet">
          <HintPath>lib\ReactWithDotNet\ReactWithDotNet.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <None Update="Version.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
        <Content Include="app.ico" />

        <Content Update="web.config">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <PropertyGroup>
        <BaseOutputPath>$(SolutionDir)bin\</BaseOutputPath>
        <OutputPath>$(SolutionDir)bin\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <AppendConfigurationToOutputPath>false</AppendConfigurationToOutputPath>
    </PropertyGroup>
    
    
</Project>
