global using System;
global using System.IO;
global using ReactWithDotNet;
global using System.Collections.Generic;
global using System.Linq;
global using static ReactWithDotNet.Mixin;
global using static ReactWithDotNet.Tailwind;
global using static ReactWithDotNet.WebColors;
global using static ApiInspector.WebUI.Extensions;
global using static ApiInspector.WebUI.Storage;
global using System.Threading.Tasks;
global using Toolbox;